"""Final fresh start

Revision ID: 02f0dee6e505
Revises: 
Create Date: 2025-11-13 21:34:32.808333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f0dee6e505'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advance_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_row', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('mappings', sa.Text(), nullable=False),
    sa.Column('vlookup_source_col', sa.String(length=50), nullable=True),
    sa.Column('vlookup_sales_col', sa.String(length=50), nullable=True),
    sa.Column('vlookup_dest_col', sa.String(length=50), nullable=True),
    sa.Column('vlookup_value_col', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('start_row', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('mappings', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bank_name')
    )
    op.create_table('sales_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_row', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('mappings', sa.Text(), nullable=False),
    sa.Column('bp_remove_cols', sa.String(length=255), nullable=True),
    sa.Column('prefix_remove_col', sa.String(length=50), nullable=True),
    sa.Column('prefix_remove_values', sa.String(length=50), nullable=True),
    sa.Column('copy_col_source', sa.String(length=50), nullable=True),
    sa.Column('copy_col_dest', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('reporting_manager', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('setting')
    op.drop_table('sales_rule')
    op.drop_table('bank_rule')
    op.drop_table('advance_rule')
    # ### end Alembic commands ###
